version: "3.8"

services:

  api-server:
    image: api-server
    restart: always
    #ports:
    #  - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
    container_name: "api-server"

  mongo:
    image: mongo
    networks:
      - mern-app
    expose:
      - "27017"
    ports:
      - "27017:27017"
    container_name: "mongo"
    volumes:
      - mongo-data:/data/db

  react-app:
    image: react-app
    stdin_open: true
    restart: always
    ports:
      - "3000:3000"
    networks:
      - mern-app
    depends_on:
      - api-server
    container_name: "react-app"

  nginx-proxy:
    image: nginx
    depends_on:
      - api-server
    ports:
      - "8000:80"
    networks:
      - mern-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: "nginx-proxy"

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
